(()=>{'use strict';
const DB='EWPL_CAMPO_DB_V1',STORE='notas'; let db;
const $=id=>document.getElementById(id), cfg=()=>window.EWPL_CAMPO_CONFIG||{};
function fechaLocal(d){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
function inferir(s){const t=(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const h=new Date();let f='',hr='';if(/\bmanana\b/.test(t)){let d=new Date(h);d.setDate(d.getDate()+1);f=fechaLocal(d)}else if(/\bhoy\b/.test(t))f=fechaLocal(h);else{const ds=['domingo','lunes','martes','miercoles','jueves','viernes','sabado'];for(let i=0;i<7;i++)if(new RegExp('\\b'+ds[i]+'\\b').test(t)){let d=new Date(h),delta=(i-d.getDay()+7)%7;if(delta===0)delta=7;d.setDate(d.getDate()+delta);f=fechaLocal(d);break}}
let m=t.match(/(?:a\s+las?\s+)?(\d{1,2})(?:[:.](\d{2}))?\s*(am|pm)?\b/);if(m){let hh=+m[1],mm=+(m[2]||0);if(m[3]==='pm'&&hh<12)hh+=12;if(m[3]==='am'&&hh===12)hh=0;if(hh<24&&mm<60)hr=String(hh).padStart(2,'0')+':'+String(mm).padStart(2,'0')}return {fecha:f,hora:hr,recordar:/recuerd|recordar|acuerd|avis|no olvidar|tengo que/.test(t)}}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function tx(mode='readonly'){return db.transaction(STORE,mode).objectStore(STORE)}
function put(x){return new Promise((res,rej)=>{const r=tx('readwrite').put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(id){return new Promise((res,rej)=>{const r=tx('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function all(){return new Promise((res,rej)=>{const r=tx().getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function id(){return 'NC:'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2))}
async function pintar(){const q=await all();$('pendientes').textContent=q.length;const on=navigator.onLine;$('estado').textContent=on?'● Con conexión':'● Sin conexión';$('estado').className='status'+(on?'':' offline')}
function mensaje(s,c=''){$('mensaje').textContent=s;$('mensaje').className='msg '+c}
async function guardar(){const texto=$('texto').value.trim();if(!texto)return mensaje('Escribe o dicta una nota.','warn');const rec=$('recordatorio').checked,fecha=$('fecha').value,hora=$('hora').value;if(rec&&(!fecha||!hora))return mensaje('Confirma fecha y hora del recordatorio.','warn');await put({id:id(),texto,creada:new Date().toISOString(),recordatorio:rec,fecha,hora,modoRecordatorio:'NORMAL',intentos:0});$('texto').value='';$('recordatorio').checked=false;$('fechaHora').classList.add('hidden');$('interpretacion').textContent='';mensaje('Nota guardada en el teléfono.','ok');await pintar();if(navigator.onLine)sincronizar()}
function configOK(){const c=cfg();return /^https:\/\/script\.google\.com\/macros\/s\/.+\/exec/.test(c.endpoint||'')&&c.token&&!String(c.token).startsWith('PEGA_')}
async function enviar(n){const c=cfg(),payload={accion:'nota',token:c.token,nota:n};try{const r=await fetch(c.endpoint,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});if(r.type!=='opaque'){const j=await r.json();if(!j||j.ok===false)throw new Error(j&&j.error||'Servidor rechazó la nota');return true}return true}catch(e){try{await fetch(c.endpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});return true}catch(_){throw e}}
}
async function sincronizar(){if(!navigator.onLine)return mensaje('Sin Internet. La nota permanece guardada.','warn');if(!configOK())return mensaje('EWPL Campo todavía no está configurado con el servidor.','warn');$('sync').disabled=true;let q=await all(),ok=0,fallos=0;for(const n of q){if(n.recordatorio&&n.fecha&&n.hora&&new Date(n.fecha+'T'+n.hora)<new Date()&&n.modoRecordatorio!=='VENCIDO'){n.recordatorio=false;n.modoRecordatorio='SOLO_ANTEFICHA'}try{await enviar(n);await del(n.id);ok++}catch(e){n.intentos=(n.intentos||0)+1;await put(n);fallos++}}
await pintar();$('sync').disabled=false;if(fallos)mensaje(`${ok} sincronizadas; ${fallos} siguen pendientes.`,'warn');else if(ok)mensaje(`${ok} nota(s) enviadas a EWPL.`,'ok')}
$('texto').addEventListener('input',()=>{const x=inferir($('texto').value);if(x.recordar||x.fecha||x.hora){$('recordatorio').checked=!!(x.recordar||x.fecha||x.hora);$('fechaHora').classList.remove('hidden');if(x.fecha)$('fecha').value=x.fecha;if(x.hora)$('hora').value=x.hora;$('interpretacion').textContent='Interpretado: '+(x.fecha||'fecha pendiente')+(x.hora?' · '+x.hora:' · hora pendiente')+' — confirma antes de guardar.'}});
$('recordatorio').addEventListener('change',()=>$('fechaHora').classList.toggle('hidden',!$('recordatorio').checked));$('guardar').onclick=guardar;$('sync').onclick=sincronizar;window.addEventListener('online',()=>{pintar();sincronizar()});window.addEventListener('offline',pintar);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&navigator.onLine)sincronizar()});
(async()=>{await openDB();await pintar();if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('./sw.js')}catch(e){}if(navigator.onLine)sincronizar()})();
})();
